[backport b8155d3] mmc: tmio, renesas_sdhi: Remove unneeded NULL check
commit b8155d3ff3ebbdfa10c6ec6c5f04b263670727e6 upstream.

The inconsistent NULL checking in this function causes static checker
warnings.

drivers/mmc/host/renesas_sdhi_sys_dmac.c:360 renesas_sdhi_sys_dmac_issue_tasklet_fn()
error: we previously assumed 'host' could be null (see line 351)

On reviewing this code, "host" can't ever be NULL so we can just remove
the check.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>